name: Build and Deploy Worker

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: |
          npx wrangler deploy src/worker.js --name bpb --compatibility-flag [nodejs_compat] --compatibility-date $(date +%Y-%m-%d) --dry-run --outdir=dist
        #npx javascript-obfuscator dist/worker.js --output _worker.js --compact true --string-array true --string-array-encoding false --string-array-encoding rc4,base64 --self-defending true --rename-globals true --transform-object-keys true

      - name: Prepare for Release
        run: |
          mkdir -p release
          cp dist/*.js release/

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: release/*
          token: ${{ secrets.TOKEN }}
          tag: v1.0.0
          releaseName: "Release v1.0.0"
          body: "This release contains the built and obfuscated worker.js."
          draft: false
          prerelease: false
